import { GoogleGenAI } from "@google/genai";
import { log } from "./index";

function detectAudioMime(buffer: Buffer): string {
  if (buffer.length < 4) return "audio/mpeg";
  if (buffer[0] === 0x52 && buffer[1] === 0x49 && buffer[2] === 0x46 && buffer[3] === 0x46) {
    return "audio/wav";
  }
  if (buffer[0] === 0x66 && buffer[1] === 0x4C && buffer[2] === 0x61 && buffer[3] === 0x43) {
    return "audio/flac";
  }
  if (buffer[0] === 0x49 && buffer[1] === 0x44 && buffer[2] === 0x33) {
    return "audio/mpeg";
  }
  if ((buffer[0] === 0xFF && (buffer[1] & 0xE0) === 0xE0)) {
    return "audio/mpeg";
  }
  if (buffer.length >= 8 && buffer[4] === 0x66 && buffer[5] === 0x74 && buffer[6] === 0x79 && buffer[7] === 0x70) {
    return "audio/mp4";
  }
  return "audio/mpeg";
}

let _ai: GoogleGenAI | null = null;

function getAI(): GoogleGenAI {
  if (!_ai) {
    if (!process.env.AI_INTEGRATIONS_GEMINI_API_KEY) {
      throw new Error("Gemini API key not configured");
    }
    _ai = new GoogleGenAI({
      apiKey: process.env.AI_INTEGRATIONS_GEMINI_API_KEY,
      httpOptions: {
        apiVersion: "",
        baseUrl: process.env.AI_INTEGRATIONS_GEMINI_BASE_URL,
      },
    });
  }
  return _ai;
}

export interface AudioAnalysis {
  overallScore: {
    ours: number;
    suno: number;
  };
  categories: {
    name: string;
    oursScore: number;
    sunoScore: number;
    analysis: string;
  }[];
  summary: string;
  recommendations: string[];
  detailedComparison: string;
}

export async function compareAudio(
  ourAudio: Buffer,
  sunoAudio: Buffer,
  context: {
    engine: string;
    prompt: string;
    lyrics?: string;
    tags?: string;
    duration: number;
  }
): Promise<AudioAnalysis> {
  log(`Starting Gemini audio comparison (our: ${ourAudio.length}b, suno: ${sunoAudio.length}b)`, "gemini");

  const ourBase64 = ourAudio.toString("base64");
  const sunoBase64 = sunoAudio.toString("base64");

  const ourMime = detectAudioMime(ourAudio);
  const sunoMime = detectAudioMime(sunoAudio);

  const systemPrompt = `You are an expert music production analyst. You will compare two AI-generated music tracks:
- Track A: Generated by "${context.engine}" engine (our system)
- Track B: Generated by Suno AI (industry standard)

Both tracks were generated from the same prompt and parameters:
- Prompt: "${context.prompt}"
${context.lyrics ? `- Lyrics: "${context.lyrics}"` : ""}
${context.tags ? `- Style/Tags: "${context.tags}"` : ""}
- Duration: ${context.duration} seconds

Analyze and compare both tracks across these categories:
1. **Audio Quality** - Clarity, bitrate artifacts, noise floor, dynamic range
2. **Vocal Quality** - Natural voice, articulation, expressiveness (if vocals present)
3. **Instrumental Quality** - Richness, arrangement, instrument separation
4. **Mixing & Mastering** - Balance, stereo image, loudness, frequency spectrum
5. **Creativity & Prompt Adherence** - How well each matches the prompt/style
6. **Song Structure** - Intro, verse, chorus, bridge, outro organization
7. **Overall Musicality** - Emotional impact, listenability, professionalism

Rate each category from 1-10 for both tracks.

Respond ONLY with valid JSON in this exact format:
{
  "overallScore": { "ours": <1-10>, "suno": <1-10> },
  "categories": [
    { "name": "<category>", "oursScore": <1-10>, "sunoScore": <1-10>, "analysis": "<brief comparison>" }
  ],
  "summary": "<2-3 sentence overall comparison>",
  "recommendations": ["<specific actionable recommendation to improve our output>", ...],
  "detailedComparison": "<detailed paragraph comparing both tracks>"
}`;

  const response = await getAI().models.generateContent({
    model: "gemini-2.5-flash",
    contents: [
      {
        role: "user",
        parts: [
          { text: systemPrompt },
          {
            inlineData: {
              mimeType: ourMime,
              data: ourBase64,
            },
          },
          { text: "This is Track A (our system)." },
          {
            inlineData: {
              mimeType: sunoMime,
              data: sunoBase64,
            },
          },
          { text: "This is Track B (Suno AI). Now compare both tracks and respond with JSON only." },
        ],
      },
    ],
  });

  const text = response.text || "";
  log(`Gemini response length: ${text.length}`, "gemini");

  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    log(`Gemini did not return valid JSON: ${text.substring(0, 500)}`, "gemini");
    throw new Error("Gemini did not return valid JSON analysis");
  }

  try {
    const analysis: AudioAnalysis = JSON.parse(jsonMatch[0]);

    if (!analysis.overallScore || !analysis.categories || !analysis.summary) {
      throw new Error("Missing required fields in analysis");
    }

    log(`Gemini analysis complete: ours=${analysis.overallScore.ours}/10, suno=${analysis.overallScore.suno}/10`, "gemini");
    return analysis;
  } catch (parseErr: any) {
    log(`Failed to parse Gemini JSON: ${parseErr.message}`, "gemini");
    throw new Error(`Failed to parse Gemini analysis: ${parseErr.message}`);
  }
}

export interface SongIdea {
  prompt: string;
  lyrics: string;
  tags: string;
  title: string;
  duration: number;
  negative_tags: string;
}

export async function generateSongIdea(engine: string = "ace-step"): Promise<SongIdea> {
  log(`Generating song idea via Gemini for engine: ${engine}`, "gemini");

  const engineContext = "ACE-Step v1.5 — an instrumental/vocal AI music generator that uses a caption-based prompt system and supports durations from 10-600 seconds. It handles both instrumental and vocal generation.";

  const ideaPrompt = `You are a creative music producer AI. Generate a unique, interesting song idea for testing an AI music generation engine.

Engine: ${engineContext}

Come up with something creative and varied — pick a random genre, mood, and theme. Be specific with the lyrics (write actual verse/chorus lyrics, not placeholders). The song should be interesting enough to properly test the engine's capabilities.

Respond ONLY with valid JSON in this exact format:
{
  "prompt": "<1-2 sentence description of the song style and mood>",
  "lyrics": "<actual song lyrics with [Verse], [Chorus], [Bridge] markers, 8-20 lines>",
  "tags": "<comma-separated style tags like: pop, energetic, female vocal, synth>",
  "title": "<creative song title>",
  "duration": <number between 30 and 120>,
  "negative_tags": "<things to avoid, e.g.: noise, distortion, off-key>"
}

Be creative! Pick unusual genres, interesting themes, and write compelling lyrics. Vary between languages occasionally. Make every idea unique.`;

  const response = await getAI().models.generateContent({
    model: "gemini-2.5-flash",
    contents: [{ role: "user", parts: [{ text: ideaPrompt }] }],
  });

  const text = response.text || "";
  log(`Gemini song idea response length: ${text.length}`, "gemini");

  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    log(`Gemini did not return valid JSON for song idea: ${text.substring(0, 500)}`, "gemini");
    throw new Error("Gemini did not return valid JSON for song idea");
  }

  try {
    const idea: SongIdea = JSON.parse(jsonMatch[0]);

    if (!idea.prompt || !idea.lyrics || !idea.tags || !idea.title) {
      throw new Error("Missing required fields in song idea");
    }

    idea.duration = Math.max(30, Math.min(300, idea.duration || 60));
    idea.negative_tags = idea.negative_tags || "";

    log(`Gemini song idea: "${idea.title}" (${idea.tags}) ${idea.duration}s`, "gemini");
    return idea;
  } catch (parseErr: any) {
    log(`Failed to parse Gemini song idea: ${parseErr.message}`, "gemini");
    throw new Error(`Failed to parse song idea: ${parseErr.message}`);
  }
}
