#!/bin/bash
set -e

IMAGE_NAME="${1:-ruslanmusin/ace-step-hf}"
TAG="${2:-latest}"

echo "Building HF Inference Endpoints image: ${IMAGE_NAME}:${TAG}"
echo "NOTE: Build for x86_64 platform (required by HF)"

docker build --platform linux/amd64 -t "${IMAGE_NAME}:${TAG}" .

echo ""
echo "Build complete: ${IMAGE_NAME}:${TAG}"
echo ""
echo "Push to Docker Hub:"
echo "  docker push ${IMAGE_NAME}:${TAG}"
echo ""
echo "Deploy on HF Inference Endpoints:"
echo "  1. Go to https://endpoints.huggingface.co/"
echo "  2. Click '+ New'"
echo "  3. Select model: ACE-Step/Ace-Step1.5"
echo "  4. Container type: Custom"
echo "  5. Docker image: ${IMAGE_NAME}:${TAG}"
echo "  6. Health route: /health"
echo "  7. GPU: A10G or A100 (16GB+ VRAM)"
echo ""
echo "Or via Python:"
echo "  from huggingface_hub import create_inference_endpoint"
echo "  endpoint = create_inference_endpoint("
echo "    'ace-step-v15',"
echo "    repository='ACE-Step/Ace-Step1.5',"
echo "    framework='custom',"
echo "    task='custom',"
echo "    accelerator='gpu',"
echo "    vendor='aws',"
echo "    region='us-east-1',"
echo "    type='protected',"
echo "    instance_size='x1',"
echo "    instance_type='nvidia-a10g',"
echo "    custom_image={"
echo "      'health_route': '/health',"
echo "      'url': '${IMAGE_NAME}:${TAG}',"
echo "      'env': {'ACESTEP_CPU_OFFLOAD': 'true'},"
echo "    },"
echo "  )"
